resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2

resources:
- name: distribution
  type: git
  icon: github-face
  source:
    uri: git@github.com:seronet-project/distribution.git
    branch: master
    depth: 5
    disable_ci_skip: false
    private_key: {{github-private-key}}
- name: registry-deployment
  type: cf
  icon: cloud-upload
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: notify
  type: slack-notification
  icon: chat-alert
  source:
    url: {{slack-webhook}}

jobs:
- name: deploy-registry
  public: false
  serial: true
  plan:
  - get: distribution
    trigger: true
  - task: build-registry
    config:
      platform: linux
      inputs:
      - name: distribution
      outputs:
      - name: distribution-output
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd distribution
          ./ci/build.sh
  - put: registry-deployment
    params:
      manifest: manifest.yml
#      current_app_name: resources
      path: distribution-output
#      environment_variables:
#        KEY: VALUE
    on_success:
      put: notify
      params:
        text: Docker registry deployed to {{cf-space}} in {{cf-org}}.   
