resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: distribution
  type: git
  icon: github-face
  source:
    uri: git@github.com:seronet-project/distribution.git
    branch: master
    depth: 5
    disable_ci_skip: false
    private_key: ((github-private-key))
- name: distribution-docker
  type: git
  icon: github-face
  source:
    uri: https://github.com/docker/distribution.git
    branch: master
    depth: 30
- name: registry-deployment
  type: cf
  icon: cloud-upload
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.org))
    space: ((cf.space))
    skip_cert_check: false
- name: notify
  type: slack-notification
  icon: chat-alert
  source:
    url: ((slack-webhook))
- name: cf-task
  type: cf-cli-resource
  source:
    org: ((cf.org))
    space: ((cf.space))
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    skip_cert_check: false
- name: merge-timer
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM
    location: Europe/Berlin
- name: gc-timer
  type: time
  source:
#   interval: 24h
    start: 3:00 AM
    stop: 4:00 AM
    location: Europe/Berlin

jobs:
- name: merge-registry
  public: false
  serial_groups: ["registry"]
  plan:
  - get: merge-timer
    trigger: true
  - get: distribution-docker
#    trigger: true
  - get: distribution
  - task: merge-distribution-docker
    config:
      platform: linux
      inputs:
      - name: distribution
      outputs:
      - name: distribution
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd distribution
          git config user.email "concourse@sero.network"
          git config user.name "SeRoNet Concourse"
          git remote add docker https://github.com/docker/distribution.git
          git fetch docker master
          git merge --no-edit docker/master
  - put: distribution
    params:
      repository: distribution  

- name: gc-registry
  public: false
  serial_groups: ["registry"]
  plan:
  - get: gc-timer
    trigger: true
  - put: cf-gc-task
    resource: cf-task
    params:
      command: run-task
      app_name: registry
      task_command: ./gc.sh
      task_name: garbage-collect
      memory: 128M
      disk_quota: 128M

- name: deploy-registry
  public: false
  serial_groups: ["registry"]
  plan:
  - get: distribution
    trigger: true
  - task: build-registry
    config:
      platform: linux
      inputs:
      - name: distribution
      outputs:
      - name: distribution-output
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd distribution
          ./ci/build.sh
  - put: registry-deployment
    params:
      manifest: distribution-output/manifest.yml
#      current_app_name: resources
      path: distribution-output
      environment_variables:
        AWS_ACCESS_KEY_ID: ((env.awsid))
        AWS_BUCKET: ((env.awsbucket))
        AWS_ENDPOINT: ((env.awsendpoint))
        AWS_SECRET_ACCESS_KEY: ((env.awskey))
        REGISTRY_HTTP_SECRET: ((env.httpsecret))
        WEBHOOK: ((env.webhook))
        AUTH_SERVICE: ((env.authservice))
    on_success:
      put: notify
      params:
        text: Docker registry deployed to ((cf.space)) in ((cf.org)).
